import { useState } from 'react';
import RoleSelect from './RoleSelect';
import Login from './Login';
import CustomerBooking from './CustomerBooking';
import WorkerDashboard from './WorkerDashboard';
import TranslationVoice from './TranslationVoice';
import ContractorDashboard from './ContractorDashboard';
import CreateProject from './CreateProject';
import WorkerSelection from './WorkerSelection';
import ProjectDetails from './ProjectDetails';
import CustomerPayment from './CustomerPayment';
import RatingSubmission from './RatingSubmission';
import ComplaintSubmission from './ComplaintSubmission';
import ComplaintSuccess from './ComplaintSuccess';
import AdminDashboard from './AdminDashboard';
import WorkerProcess from './WorkerProcess';
import ProjectAssigned from './projectAssigned';
import WorkProcessStarted from './WorkProcessStarted';
import PaymentSuccess from './PaymentSuccess';

function App() {
  const [page, setPage] = useState('home'); const [selectedRole, setSelectedRole] = useState(''); const [selectedWorker, setSelectedWorker] = useState(null); const [bookingId, setBookingId] = useState(null); const [project, setProject] = useState(null); const [selectedWorkers, setSelectedWorkers] = useState([]);
  const back=()=>{const map={translationVoice:'home',role:'translationVoice',login:'role',customerBooking:'login',workerProcess:'customerBooking',customerPayment:'workerProcess',paymentSuccess:'customerPayment',ratingSubmission:'paymentSuccess',complaintSubmission:'ratingSubmission',complaintSuccess:'home',workerDashboard:'login',contractorDashboard:'login',createProject:'contractorDashboard',workerSelection:'createProject',projectDetails:'workerSelection',projectAssigned:'projectDetails',WorkProcessStarted:'contractorDashboard',adminDashboard:'login'};setPage(map[page]||'home');};
  if(page==='translationVoice')return <TranslationVoice onBack={()=>setPage('home')} onContinue={()=>setPage('role')}/>;
  if(page==='role')return <RoleSelect onSelect={r=>{setSelectedRole(r);setPage('login')}} onBack={back}/>;
  if(page==='login')return <Login role={selectedRole} onSuccess={()=>setPage(selectedRole==='customer'?'customerBooking':selectedRole==='worker'?'workerDashboard':selectedRole==='contractor'?'contractorDashboard':'adminDashboard')} onBack={back}/>;
  if(page==='customerBooking')return <CustomerBooking onBack={back} onSelectWorker={(worker,id)=>{setSelectedWorker(worker);setBookingId(id);setPage('workerProcess')}}/>;
  if(page==='workerProcess')return <WorkerProcess worker={selectedWorker} bookingId={bookingId} onBack={back} onProceedToPayment={()=>setPage('customerPayment')}/>;
  if(page==='customerPayment')return <CustomerPayment worker={selectedWorker} bookingId={bookingId} onBack={back} onNext={()=>setPage('paymentSuccess')}/>;
  if(page==='paymentSuccess')return <PaymentSuccess onBack={back} onContinue={()=>setPage('ratingSubmission')}/>;
  if(page==='ratingSubmission')return <RatingSubmission bookingId={bookingId} onBack={back} onSubmit={()=>setPage('home')} onComplaint={()=>setPage('complaintSubmission')}/>;
  if(page==='complaintSubmission')return <ComplaintSubmission bookingId={bookingId} onBack={back} onSubmit={()=>setPage('complaintSuccess')}/>;
  if(page==='complaintSuccess')return <ComplaintSuccess onBack={()=>setPage('home')}/>;
  if(page==='workerDashboard')return <WorkerDashboard onBack={back}/>;
  if(page==='contractorDashboard')return <ContractorDashboard onBack={back} onCreateProject={()=>{setProject(null);setSelectedWorkers([]);setPage('createProject')}}/>;
  if(page==='createProject')return <CreateProject onBack={back} onNext={p=>{setProject(p);setSelectedWorkers([]);setPage('workerSelection')}}/>;
  if(page==='workerSelection')return <WorkerSelection project={project} onBack={back} onNext={w=>{setSelectedWorkers(w);setPage('projectDetails')}}/>;
  if(page==='projectDetails')return <ProjectDetails project={project} selectedWorkers={selectedWorkers} onBack={back} onCreateProject={()=>setPage('projectAssigned')}/>;
  if(page==='projectAssigned')return <ProjectAssigned project={project} selectedWorkers={selectedWorkers} onBack={back} onContinue={()=>setPage('WorkProcessStarted')}/>;
  if(page==='WorkProcessStarted')return <WorkProcessStarted onDashboard={()=>setPage('contractorDashboard')}/>;
  if(page==='adminDashboard')return <AdminDashboard onBack={back}/>;
  return <main className="min-h-screen bg-[#FFF1E6] text-slate-900"><nav className="flex items-center justify-between px-6 py-5 sm:px-8"><div className="flex items-center gap-3"><img src="/anvaya-logo.png" alt="Anvaya" className="h-12 w-auto"/><span className="hidden border-l border-amber-200 pl-3 text-sm font-semibold text-slate-600 sm:block">Local services, made easier</span></div><button onClick={()=>setPage('translationVoice')} className="rounded-xl border border-amber-200 bg-white px-5 py-2.5 font-semibold shadow-sm">Get Started</button></nav><section className="flex min-h-[calc(100vh-88px)] flex-col items-center justify-center px-6 pb-16 text-center"><div className="rounded-full border border-amber-200 bg-white px-5 py-2 text-sm font-semibold text-amber-800">✨ Trusted Local Workers</div><img src="/anvaya-logo.png" alt="Anvaya" className="mt-6 h-40 sm:h-48"/><h1 className="mt-5 max-w-4xl text-4xl font-bold sm:text-6xl">Find Trusted Workers <span className="text-amber-600">Near You</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">Connect with verified electricians, plumbers, carpenters, painters, masons and other skilled professionals for your everyday needs.</p><button onClick={()=>setPage('translationVoice')} className="mt-9 rounded-2xl bg-amber-600 px-8 py-4 font-bold text-white shadow-xl">Get Started →</button><p className="mt-12 text-sm text-slate-400">Trusted workers. Better connections. Stronger communities.</p></section></main>;
}
export default App;